/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as GuruRouteRouteImport } from './routes/guru/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrtuRouteRouteImport } from './routes/ortu/route'
import { Route as SuperAdminRouteRouteImport } from './routes/super-admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBiayaAiRouteImport } from './routes/admin/biaya-ai'
import { Route as AdminDataMassalRouteImport } from './routes/admin/data-massal'
import { Route as AdminGuruRouteImport } from './routes/admin/guru'
import { Route as AdminKelasRouteImport } from './routes/admin/kelas'
import { Route as AdminOrtuRouteImport } from './routes/admin/ortu'
import { Route as AdminSiswaRouteImport } from './routes/admin/siswa'
import { Route as GuruIndexRouteImport } from './routes/guru/index'
import { Route as GuruCatatObservasiRouteImport } from './routes/guru/catat-observasi'
import { Route as GuruLaporanOrangTuaRouteImport } from './routes/guru/laporan-orang-tua'
import { Route as GuruObservasiMingguanRouteImport } from './routes/guru/observasi-mingguan'
import { Route as GuruRingkasanRouteImport } from './routes/guru/ringkasan'
import { Route as OrtuIndexRouteImport } from './routes/ortu/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as SuperAdminTenantAdminsRouteImport } from './routes/super-admin/tenant-admins'
import { Route as SuperAdminTenantsRouteImport } from './routes/super-admin/tenants'
import { Route as AdminGuruNewRouteImport } from './routes/admin/guru_.new'
import { Route as AdminKelasNewRouteImport } from './routes/admin/kelas_.new'
import { Route as AdminOrtuNewRouteImport } from './routes/admin/ortu_.new'
import { Route as AdminSiswaNewRouteImport } from './routes/admin/siswa_.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SuperAdminTenantAdminsNewRouteImport } from './routes/super-admin/tenant-admins_.new'
import { Route as SuperAdminTenantsNewRouteImport } from './routes/super-admin/tenants_.new'
import { Route as AdminGuruTeacherIdEditRouteImport } from './routes/admin/guru_.$teacherId.edit'
import { Route as AdminKelasClassIdEditRouteImport } from './routes/admin/kelas_.$classId.edit'
import { Route as AdminOrtuParentIdEditRouteImport } from './routes/admin/ortu_.$parentId.edit'
import { Route as AdminSiswaStudentIdEditRouteImport } from './routes/admin/siswa_.$studentId.edit'
import { Route as SuperAdminTenantAdminsAdminIdEditRouteImport } from './routes/super-admin/tenant-admins_.$adminId.edit'
import { Route as SuperAdminTenantsTenantIdEditRouteImport } from './routes/super-admin/tenants_.$tenantId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruRouteRoute = GuruRouteRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtuRouteRoute = OrtuRouteRouteImport.update({
  id: '/ortu',
  path: '/ortu',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRouteRoute = SuperAdminRouteRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBiayaAiRoute = AdminBiayaAiRouteImport.update({
  id: '/biaya-ai',
  path: '/biaya-ai',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataMassalRoute = AdminDataMassalRouteImport.update({
  id: '/data-massal',
  path: '/data-massal',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGuruRoute = AdminGuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKelasRoute = AdminKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrtuRoute = AdminOrtuRouteImport.update({
  id: '/ortu',
  path: '/ortu',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiswaRoute = AdminSiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuruIndexRoute = GuruIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuruRouteRoute,
} as any)
const GuruCatatObservasiRoute = GuruCatatObservasiRouteImport.update({
  id: '/catat-observasi',
  path: '/catat-observasi',
  getParentRoute: () => GuruRouteRoute,
} as any)
const GuruLaporanOrangTuaRoute = GuruLaporanOrangTuaRouteImport.update({
  id: '/laporan-orang-tua',
  path: '/laporan-orang-tua',
  getParentRoute: () => GuruRouteRoute,
} as any)
const GuruObservasiMingguanRoute = GuruObservasiMingguanRouteImport.update({
  id: '/observasi-mingguan',
  path: '/observasi-mingguan',
  getParentRoute: () => GuruRouteRoute,
} as any)
const GuruRingkasanRoute = GuruRingkasanRouteImport.update({
  id: '/ringkasan',
  path: '/ringkasan',
  getParentRoute: () => GuruRouteRoute,
} as any)
const OrtuIndexRoute = OrtuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrtuRouteRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminTenantAdminsRoute = SuperAdminTenantAdminsRouteImport.update({
  id: '/tenant-admins',
  path: '/tenant-admins',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminTenantsRoute = SuperAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const AdminGuruNewRoute = AdminGuruNewRouteImport.update({
  id: '/guru_/new',
  path: '/guru/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKelasNewRoute = AdminKelasNewRouteImport.update({
  id: '/kelas_/new',
  path: '/kelas/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrtuNewRoute = AdminOrtuNewRouteImport.update({
  id: '/ortu_/new',
  path: '/ortu/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiswaNewRoute = AdminSiswaNewRouteImport.update({
  id: '/siswa_/new',
  path: '/siswa/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminTenantAdminsNewRoute =
  SuperAdminTenantAdminsNewRouteImport.update({
    id: '/tenant-admins_/new',
    path: '/tenant-admins/new',
    getParentRoute: () => SuperAdminRouteRoute,
  } as any)
const SuperAdminTenantsNewRoute = SuperAdminTenantsNewRouteImport.update({
  id: '/tenants_/new',
  path: '/tenants/new',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const AdminGuruTeacherIdEditRoute = AdminGuruTeacherIdEditRouteImport.update({
  id: '/guru_/$teacherId/edit',
  path: '/guru/$teacherId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKelasClassIdEditRoute = AdminKelasClassIdEditRouteImport.update({
  id: '/kelas_/$classId/edit',
  path: '/kelas/$classId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrtuParentIdEditRoute = AdminOrtuParentIdEditRouteImport.update({
  id: '/ortu_/$parentId/edit',
  path: '/ortu/$parentId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiswaStudentIdEditRoute = AdminSiswaStudentIdEditRouteImport.update({
  id: '/siswa_/$studentId/edit',
  path: '/siswa/$studentId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SuperAdminTenantAdminsAdminIdEditRoute =
  SuperAdminTenantAdminsAdminIdEditRouteImport.update({
    id: '/tenant-admins_/$adminId/edit',
    path: '/tenant-admins/$adminId/edit',
    getParentRoute: () => SuperAdminRouteRoute,
  } as any)
const SuperAdminTenantsTenantIdEditRoute =
  SuperAdminTenantsTenantIdEditRouteImport.update({
    id: '/tenants_/$tenantId/edit',
    path: '/tenants/$tenantId/edit',
    getParentRoute: () => SuperAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/guru': typeof GuruRouteRouteWithChildren
  '/ortu': typeof OrtuRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/biaya-ai': typeof AdminBiayaAiRoute
  '/admin/data-massal': typeof AdminDataMassalRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/ortu': typeof AdminOrtuRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/guru/catat-observasi': typeof GuruCatatObservasiRoute
  '/guru/laporan-orang-tua': typeof GuruLaporanOrangTuaRoute
  '/guru/observasi-mingguan': typeof GuruObservasiMingguanRoute
  '/guru/ringkasan': typeof GuruRingkasanRoute
  '/super-admin/tenant-admins': typeof SuperAdminTenantAdminsRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/admin/': typeof AdminIndexRoute
  '/guru/': typeof GuruIndexRoute
  '/ortu/': typeof OrtuIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/guru/new': typeof AdminGuruNewRoute
  '/admin/kelas/new': typeof AdminKelasNewRoute
  '/admin/ortu/new': typeof AdminOrtuNewRoute
  '/admin/siswa/new': typeof AdminSiswaNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/super-admin/tenant-admins/new': typeof SuperAdminTenantAdminsNewRoute
  '/super-admin/tenants/new': typeof SuperAdminTenantsNewRoute
  '/admin/guru/$teacherId/edit': typeof AdminGuruTeacherIdEditRoute
  '/admin/kelas/$classId/edit': typeof AdminKelasClassIdEditRoute
  '/admin/ortu/$parentId/edit': typeof AdminOrtuParentIdEditRoute
  '/admin/siswa/$studentId/edit': typeof AdminSiswaStudentIdEditRoute
  '/super-admin/tenant-admins/$adminId/edit': typeof SuperAdminTenantAdminsAdminIdEditRoute
  '/super-admin/tenants/$tenantId/edit': typeof SuperAdminTenantsTenantIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/biaya-ai': typeof AdminBiayaAiRoute
  '/admin/data-massal': typeof AdminDataMassalRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/ortu': typeof AdminOrtuRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/guru/catat-observasi': typeof GuruCatatObservasiRoute
  '/guru/laporan-orang-tua': typeof GuruLaporanOrangTuaRoute
  '/guru/observasi-mingguan': typeof GuruObservasiMingguanRoute
  '/guru/ringkasan': typeof GuruRingkasanRoute
  '/super-admin/tenant-admins': typeof SuperAdminTenantAdminsRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/admin': typeof AdminIndexRoute
  '/guru': typeof GuruIndexRoute
  '/ortu': typeof OrtuIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/admin/guru/new': typeof AdminGuruNewRoute
  '/admin/kelas/new': typeof AdminKelasNewRoute
  '/admin/ortu/new': typeof AdminOrtuNewRoute
  '/admin/siswa/new': typeof AdminSiswaNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/super-admin/tenant-admins/new': typeof SuperAdminTenantAdminsNewRoute
  '/super-admin/tenants/new': typeof SuperAdminTenantsNewRoute
  '/admin/guru/$teacherId/edit': typeof AdminGuruTeacherIdEditRoute
  '/admin/kelas/$classId/edit': typeof AdminKelasClassIdEditRoute
  '/admin/ortu/$parentId/edit': typeof AdminOrtuParentIdEditRoute
  '/admin/siswa/$studentId/edit': typeof AdminSiswaStudentIdEditRoute
  '/super-admin/tenant-admins/$adminId/edit': typeof SuperAdminTenantAdminsAdminIdEditRoute
  '/super-admin/tenants/$tenantId/edit': typeof SuperAdminTenantsTenantIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/guru': typeof GuruRouteRouteWithChildren
  '/ortu': typeof OrtuRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/biaya-ai': typeof AdminBiayaAiRoute
  '/admin/data-massal': typeof AdminDataMassalRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/ortu': typeof AdminOrtuRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/guru/catat-observasi': typeof GuruCatatObservasiRoute
  '/guru/laporan-orang-tua': typeof GuruLaporanOrangTuaRoute
  '/guru/observasi-mingguan': typeof GuruObservasiMingguanRoute
  '/guru/ringkasan': typeof GuruRingkasanRoute
  '/super-admin/tenant-admins': typeof SuperAdminTenantAdminsRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/admin/': typeof AdminIndexRoute
  '/guru/': typeof GuruIndexRoute
  '/ortu/': typeof OrtuIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/guru_/new': typeof AdminGuruNewRoute
  '/admin/kelas_/new': typeof AdminKelasNewRoute
  '/admin/ortu_/new': typeof AdminOrtuNewRoute
  '/admin/siswa_/new': typeof AdminSiswaNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/super-admin/tenant-admins_/new': typeof SuperAdminTenantAdminsNewRoute
  '/super-admin/tenants_/new': typeof SuperAdminTenantsNewRoute
  '/admin/guru_/$teacherId/edit': typeof AdminGuruTeacherIdEditRoute
  '/admin/kelas_/$classId/edit': typeof AdminKelasClassIdEditRoute
  '/admin/ortu_/$parentId/edit': typeof AdminOrtuParentIdEditRoute
  '/admin/siswa_/$studentId/edit': typeof AdminSiswaStudentIdEditRoute
  '/super-admin/tenant-admins_/$adminId/edit': typeof SuperAdminTenantAdminsAdminIdEditRoute
  '/super-admin/tenants_/$tenantId/edit': typeof SuperAdminTenantsTenantIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/guru'
    | '/ortu'
    | '/super-admin'
    | '/login'
    | '/admin/biaya-ai'
    | '/admin/data-massal'
    | '/admin/guru'
    | '/admin/kelas'
    | '/admin/ortu'
    | '/admin/siswa'
    | '/guru/catat-observasi'
    | '/guru/laporan-orang-tua'
    | '/guru/observasi-mingguan'
    | '/guru/ringkasan'
    | '/super-admin/tenant-admins'
    | '/super-admin/tenants'
    | '/admin/'
    | '/guru/'
    | '/ortu/'
    | '/super-admin/'
    | '/admin/guru/new'
    | '/admin/kelas/new'
    | '/admin/ortu/new'
    | '/admin/siswa/new'
    | '/api/auth/$'
    | '/super-admin/tenant-admins/new'
    | '/super-admin/tenants/new'
    | '/admin/guru/$teacherId/edit'
    | '/admin/kelas/$classId/edit'
    | '/admin/ortu/$parentId/edit'
    | '/admin/siswa/$studentId/edit'
    | '/super-admin/tenant-admins/$adminId/edit'
    | '/super-admin/tenants/$tenantId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/biaya-ai'
    | '/admin/data-massal'
    | '/admin/guru'
    | '/admin/kelas'
    | '/admin/ortu'
    | '/admin/siswa'
    | '/guru/catat-observasi'
    | '/guru/laporan-orang-tua'
    | '/guru/observasi-mingguan'
    | '/guru/ringkasan'
    | '/super-admin/tenant-admins'
    | '/super-admin/tenants'
    | '/admin'
    | '/guru'
    | '/ortu'
    | '/super-admin'
    | '/admin/guru/new'
    | '/admin/kelas/new'
    | '/admin/ortu/new'
    | '/admin/siswa/new'
    | '/api/auth/$'
    | '/super-admin/tenant-admins/new'
    | '/super-admin/tenants/new'
    | '/admin/guru/$teacherId/edit'
    | '/admin/kelas/$classId/edit'
    | '/admin/ortu/$parentId/edit'
    | '/admin/siswa/$studentId/edit'
    | '/super-admin/tenant-admins/$adminId/edit'
    | '/super-admin/tenants/$tenantId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/guru'
    | '/ortu'
    | '/super-admin'
    | '/login'
    | '/admin/biaya-ai'
    | '/admin/data-massal'
    | '/admin/guru'
    | '/admin/kelas'
    | '/admin/ortu'
    | '/admin/siswa'
    | '/guru/catat-observasi'
    | '/guru/laporan-orang-tua'
    | '/guru/observasi-mingguan'
    | '/guru/ringkasan'
    | '/super-admin/tenant-admins'
    | '/super-admin/tenants'
    | '/admin/'
    | '/guru/'
    | '/ortu/'
    | '/super-admin/'
    | '/admin/guru_/new'
    | '/admin/kelas_/new'
    | '/admin/ortu_/new'
    | '/admin/siswa_/new'
    | '/api/auth/$'
    | '/super-admin/tenant-admins_/new'
    | '/super-admin/tenants_/new'
    | '/admin/guru_/$teacherId/edit'
    | '/admin/kelas_/$classId/edit'
    | '/admin/ortu_/$parentId/edit'
    | '/admin/siswa_/$studentId/edit'
    | '/super-admin/tenant-admins_/$adminId/edit'
    | '/super-admin/tenants_/$tenantId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  GuruRouteRoute: typeof GuruRouteRouteWithChildren
  OrtuRouteRoute: typeof OrtuRouteRouteWithChildren
  SuperAdminRouteRoute: typeof SuperAdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru': {
      id: '/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof GuruRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ortu': {
      id: '/ortu'
      path: '/ortu'
      fullPath: '/ortu'
      preLoaderRoute: typeof OrtuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/biaya-ai': {
      id: '/admin/biaya-ai'
      path: '/biaya-ai'
      fullPath: '/admin/biaya-ai'
      preLoaderRoute: typeof AdminBiayaAiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-massal': {
      id: '/admin/data-massal'
      path: '/data-massal'
      fullPath: '/admin/data-massal'
      preLoaderRoute: typeof AdminDataMassalRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/guru': {
      id: '/admin/guru'
      path: '/guru'
      fullPath: '/admin/guru'
      preLoaderRoute: typeof AdminGuruRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kelas': {
      id: '/admin/kelas'
      path: '/kelas'
      fullPath: '/admin/kelas'
      preLoaderRoute: typeof AdminKelasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ortu': {
      id: '/admin/ortu'
      path: '/ortu'
      fullPath: '/admin/ortu'
      preLoaderRoute: typeof AdminOrtuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/siswa': {
      id: '/admin/siswa'
      path: '/siswa'
      fullPath: '/admin/siswa'
      preLoaderRoute: typeof AdminSiswaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guru/': {
      id: '/guru/'
      path: '/'
      fullPath: '/guru/'
      preLoaderRoute: typeof GuruIndexRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/guru/catat-observasi': {
      id: '/guru/catat-observasi'
      path: '/catat-observasi'
      fullPath: '/guru/catat-observasi'
      preLoaderRoute: typeof GuruCatatObservasiRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/guru/laporan-orang-tua': {
      id: '/guru/laporan-orang-tua'
      path: '/laporan-orang-tua'
      fullPath: '/guru/laporan-orang-tua'
      preLoaderRoute: typeof GuruLaporanOrangTuaRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/guru/observasi-mingguan': {
      id: '/guru/observasi-mingguan'
      path: '/observasi-mingguan'
      fullPath: '/guru/observasi-mingguan'
      preLoaderRoute: typeof GuruObservasiMingguanRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/guru/ringkasan': {
      id: '/guru/ringkasan'
      path: '/ringkasan'
      fullPath: '/guru/ringkasan'
      preLoaderRoute: typeof GuruRingkasanRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/ortu/': {
      id: '/ortu/'
      path: '/'
      fullPath: '/ortu/'
      preLoaderRoute: typeof OrtuIndexRouteImport
      parentRoute: typeof OrtuRouteRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/tenant-admins': {
      id: '/super-admin/tenant-admins'
      path: '/tenant-admins'
      fullPath: '/super-admin/tenant-admins'
      preLoaderRoute: typeof SuperAdminTenantAdminsRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/tenants': {
      id: '/super-admin/tenants'
      path: '/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof SuperAdminTenantsRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/admin/guru_/new': {
      id: '/admin/guru_/new'
      path: '/guru/new'
      fullPath: '/admin/guru/new'
      preLoaderRoute: typeof AdminGuruNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kelas_/new': {
      id: '/admin/kelas_/new'
      path: '/kelas/new'
      fullPath: '/admin/kelas/new'
      preLoaderRoute: typeof AdminKelasNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ortu_/new': {
      id: '/admin/ortu_/new'
      path: '/ortu/new'
      fullPath: '/admin/ortu/new'
      preLoaderRoute: typeof AdminOrtuNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/siswa_/new': {
      id: '/admin/siswa_/new'
      path: '/siswa/new'
      fullPath: '/admin/siswa/new'
      preLoaderRoute: typeof AdminSiswaNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/tenant-admins_/new': {
      id: '/super-admin/tenant-admins_/new'
      path: '/tenant-admins/new'
      fullPath: '/super-admin/tenant-admins/new'
      preLoaderRoute: typeof SuperAdminTenantAdminsNewRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/tenants_/new': {
      id: '/super-admin/tenants_/new'
      path: '/tenants/new'
      fullPath: '/super-admin/tenants/new'
      preLoaderRoute: typeof SuperAdminTenantsNewRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/admin/guru_/$teacherId/edit': {
      id: '/admin/guru_/$teacherId/edit'
      path: '/guru/$teacherId/edit'
      fullPath: '/admin/guru/$teacherId/edit'
      preLoaderRoute: typeof AdminGuruTeacherIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kelas_/$classId/edit': {
      id: '/admin/kelas_/$classId/edit'
      path: '/kelas/$classId/edit'
      fullPath: '/admin/kelas/$classId/edit'
      preLoaderRoute: typeof AdminKelasClassIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ortu_/$parentId/edit': {
      id: '/admin/ortu_/$parentId/edit'
      path: '/ortu/$parentId/edit'
      fullPath: '/admin/ortu/$parentId/edit'
      preLoaderRoute: typeof AdminOrtuParentIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/siswa_/$studentId/edit': {
      id: '/admin/siswa_/$studentId/edit'
      path: '/siswa/$studentId/edit'
      fullPath: '/admin/siswa/$studentId/edit'
      preLoaderRoute: typeof AdminSiswaStudentIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/super-admin/tenant-admins_/$adminId/edit': {
      id: '/super-admin/tenant-admins_/$adminId/edit'
      path: '/tenant-admins/$adminId/edit'
      fullPath: '/super-admin/tenant-admins/$adminId/edit'
      preLoaderRoute: typeof SuperAdminTenantAdminsAdminIdEditRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/tenants_/$tenantId/edit': {
      id: '/super-admin/tenants_/$tenantId/edit'
      path: '/tenants/$tenantId/edit'
      fullPath: '/super-admin/tenants/$tenantId/edit'
      preLoaderRoute: typeof SuperAdminTenantsTenantIdEditRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBiayaAiRoute: typeof AdminBiayaAiRoute
  AdminDataMassalRoute: typeof AdminDataMassalRoute
  AdminGuruRoute: typeof AdminGuruRoute
  AdminKelasRoute: typeof AdminKelasRoute
  AdminOrtuRoute: typeof AdminOrtuRoute
  AdminSiswaRoute: typeof AdminSiswaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminGuruNewRoute: typeof AdminGuruNewRoute
  AdminKelasNewRoute: typeof AdminKelasNewRoute
  AdminOrtuNewRoute: typeof AdminOrtuNewRoute
  AdminSiswaNewRoute: typeof AdminSiswaNewRoute
  AdminGuruTeacherIdEditRoute: typeof AdminGuruTeacherIdEditRoute
  AdminKelasClassIdEditRoute: typeof AdminKelasClassIdEditRoute
  AdminOrtuParentIdEditRoute: typeof AdminOrtuParentIdEditRoute
  AdminSiswaStudentIdEditRoute: typeof AdminSiswaStudentIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBiayaAiRoute: AdminBiayaAiRoute,
  AdminDataMassalRoute: AdminDataMassalRoute,
  AdminGuruRoute: AdminGuruRoute,
  AdminKelasRoute: AdminKelasRoute,
  AdminOrtuRoute: AdminOrtuRoute,
  AdminSiswaRoute: AdminSiswaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminGuruNewRoute: AdminGuruNewRoute,
  AdminKelasNewRoute: AdminKelasNewRoute,
  AdminOrtuNewRoute: AdminOrtuNewRoute,
  AdminSiswaNewRoute: AdminSiswaNewRoute,
  AdminGuruTeacherIdEditRoute: AdminGuruTeacherIdEditRoute,
  AdminKelasClassIdEditRoute: AdminKelasClassIdEditRoute,
  AdminOrtuParentIdEditRoute: AdminOrtuParentIdEditRoute,
  AdminSiswaStudentIdEditRoute: AdminSiswaStudentIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface GuruRouteRouteChildren {
  GuruCatatObservasiRoute: typeof GuruCatatObservasiRoute
  GuruLaporanOrangTuaRoute: typeof GuruLaporanOrangTuaRoute
  GuruObservasiMingguanRoute: typeof GuruObservasiMingguanRoute
  GuruRingkasanRoute: typeof GuruRingkasanRoute
  GuruIndexRoute: typeof GuruIndexRoute
}

const GuruRouteRouteChildren: GuruRouteRouteChildren = {
  GuruCatatObservasiRoute: GuruCatatObservasiRoute,
  GuruLaporanOrangTuaRoute: GuruLaporanOrangTuaRoute,
  GuruObservasiMingguanRoute: GuruObservasiMingguanRoute,
  GuruRingkasanRoute: GuruRingkasanRoute,
  GuruIndexRoute: GuruIndexRoute,
}

const GuruRouteRouteWithChildren = GuruRouteRoute._addFileChildren(
  GuruRouteRouteChildren,
)

interface OrtuRouteRouteChildren {
  OrtuIndexRoute: typeof OrtuIndexRoute
}

const OrtuRouteRouteChildren: OrtuRouteRouteChildren = {
  OrtuIndexRoute: OrtuIndexRoute,
}

const OrtuRouteRouteWithChildren = OrtuRouteRoute._addFileChildren(
  OrtuRouteRouteChildren,
)

interface SuperAdminRouteRouteChildren {
  SuperAdminTenantAdminsRoute: typeof SuperAdminTenantAdminsRoute
  SuperAdminTenantsRoute: typeof SuperAdminTenantsRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  SuperAdminTenantAdminsNewRoute: typeof SuperAdminTenantAdminsNewRoute
  SuperAdminTenantsNewRoute: typeof SuperAdminTenantsNewRoute
  SuperAdminTenantAdminsAdminIdEditRoute: typeof SuperAdminTenantAdminsAdminIdEditRoute
  SuperAdminTenantsTenantIdEditRoute: typeof SuperAdminTenantsTenantIdEditRoute
}

const SuperAdminRouteRouteChildren: SuperAdminRouteRouteChildren = {
  SuperAdminTenantAdminsRoute: SuperAdminTenantAdminsRoute,
  SuperAdminTenantsRoute: SuperAdminTenantsRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  SuperAdminTenantAdminsNewRoute: SuperAdminTenantAdminsNewRoute,
  SuperAdminTenantsNewRoute: SuperAdminTenantsNewRoute,
  SuperAdminTenantAdminsAdminIdEditRoute:
    SuperAdminTenantAdminsAdminIdEditRoute,
  SuperAdminTenantsTenantIdEditRoute: SuperAdminTenantsTenantIdEditRoute,
}

const SuperAdminRouteRouteWithChildren = SuperAdminRouteRoute._addFileChildren(
  SuperAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  GuruRouteRoute: GuruRouteRouteWithChildren,
  OrtuRouteRoute: OrtuRouteRouteWithChildren,
  SuperAdminRouteRoute: SuperAdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
