/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrtuRouteRouteImport } from './routes/ortu/route'
import { Route as GuruRouteRouteImport } from './routes/guru/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrtuIndexRouteImport } from './routes/ortu/index'
import { Route as GuruIndexRouteImport } from './routes/guru/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GuruRingkasanRouteImport } from './routes/guru/ringkasan'
import { Route as GuruObservasiMingguanRouteImport } from './routes/guru/observasi-mingguan'
import { Route as GuruCatatObservasiRouteImport } from './routes/guru/catat-observasi'
import { Route as AdminSiswaRouteImport } from './routes/admin/siswa'
import { Route as AdminOrtuRouteImport } from './routes/admin/ortu'
import { Route as AdminKelasRouteImport } from './routes/admin/kelas'
import { Route as AdminGuruRouteImport } from './routes/admin/guru'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtuRouteRoute = OrtuRouteRouteImport.update({
  id: '/ortu',
  path: '/ortu',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruRouteRoute = GuruRouteRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtuIndexRoute = OrtuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrtuRouteRoute,
} as any)
const GuruIndexRoute = GuruIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuruRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuruRingkasanRoute = GuruRingkasanRouteImport.update({
  id: '/ringkasan',
  path: '/ringkasan',
  getParentRoute: () => GuruRouteRoute,
} as any)
const GuruObservasiMingguanRoute = GuruObservasiMingguanRouteImport.update({
  id: '/observasi-mingguan',
  path: '/observasi-mingguan',
  getParentRoute: () => GuruRouteRoute,
} as any)
const GuruCatatObservasiRoute = GuruCatatObservasiRouteImport.update({
  id: '/catat-observasi',
  path: '/catat-observasi',
  getParentRoute: () => GuruRouteRoute,
} as any)
const AdminSiswaRoute = AdminSiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrtuRoute = AdminOrtuRouteImport.update({
  id: '/ortu',
  path: '/ortu',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKelasRoute = AdminKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGuruRoute = AdminGuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/guru': typeof GuruRouteRouteWithChildren
  '/ortu': typeof OrtuRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/ortu': typeof AdminOrtuRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/guru/catat-observasi': typeof GuruCatatObservasiRoute
  '/guru/observasi-mingguan': typeof GuruObservasiMingguanRoute
  '/guru/ringkasan': typeof GuruRingkasanRoute
  '/admin/': typeof AdminIndexRoute
  '/guru/': typeof GuruIndexRoute
  '/ortu/': typeof OrtuIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/ortu': typeof AdminOrtuRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/guru/catat-observasi': typeof GuruCatatObservasiRoute
  '/guru/observasi-mingguan': typeof GuruObservasiMingguanRoute
  '/guru/ringkasan': typeof GuruRingkasanRoute
  '/admin': typeof AdminIndexRoute
  '/guru': typeof GuruIndexRoute
  '/ortu': typeof OrtuIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/guru': typeof GuruRouteRouteWithChildren
  '/ortu': typeof OrtuRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/ortu': typeof AdminOrtuRoute
  '/admin/siswa': typeof AdminSiswaRoute
  '/guru/catat-observasi': typeof GuruCatatObservasiRoute
  '/guru/observasi-mingguan': typeof GuruObservasiMingguanRoute
  '/guru/ringkasan': typeof GuruRingkasanRoute
  '/admin/': typeof AdminIndexRoute
  '/guru/': typeof GuruIndexRoute
  '/ortu/': typeof OrtuIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/guru'
    | '/ortu'
    | '/login'
    | '/admin/guru'
    | '/admin/kelas'
    | '/admin/ortu'
    | '/admin/siswa'
    | '/guru/catat-observasi'
    | '/guru/observasi-mingguan'
    | '/guru/ringkasan'
    | '/admin/'
    | '/guru/'
    | '/ortu/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/guru'
    | '/admin/kelas'
    | '/admin/ortu'
    | '/admin/siswa'
    | '/guru/catat-observasi'
    | '/guru/observasi-mingguan'
    | '/guru/ringkasan'
    | '/admin'
    | '/guru'
    | '/ortu'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/guru'
    | '/ortu'
    | '/login'
    | '/admin/guru'
    | '/admin/kelas'
    | '/admin/ortu'
    | '/admin/siswa'
    | '/guru/catat-observasi'
    | '/guru/observasi-mingguan'
    | '/guru/ringkasan'
    | '/admin/'
    | '/guru/'
    | '/ortu/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  GuruRouteRoute: typeof GuruRouteRouteWithChildren
  OrtuRouteRoute: typeof OrtuRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ortu': {
      id: '/ortu'
      path: '/ortu'
      fullPath: '/ortu'
      preLoaderRoute: typeof OrtuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru': {
      id: '/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof GuruRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ortu/': {
      id: '/ortu/'
      path: '/'
      fullPath: '/ortu/'
      preLoaderRoute: typeof OrtuIndexRouteImport
      parentRoute: typeof OrtuRouteRoute
    }
    '/guru/': {
      id: '/guru/'
      path: '/'
      fullPath: '/guru/'
      preLoaderRoute: typeof GuruIndexRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guru/ringkasan': {
      id: '/guru/ringkasan'
      path: '/ringkasan'
      fullPath: '/guru/ringkasan'
      preLoaderRoute: typeof GuruRingkasanRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/guru/observasi-mingguan': {
      id: '/guru/observasi-mingguan'
      path: '/observasi-mingguan'
      fullPath: '/guru/observasi-mingguan'
      preLoaderRoute: typeof GuruObservasiMingguanRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/guru/catat-observasi': {
      id: '/guru/catat-observasi'
      path: '/catat-observasi'
      fullPath: '/guru/catat-observasi'
      preLoaderRoute: typeof GuruCatatObservasiRouteImport
      parentRoute: typeof GuruRouteRoute
    }
    '/admin/siswa': {
      id: '/admin/siswa'
      path: '/siswa'
      fullPath: '/admin/siswa'
      preLoaderRoute: typeof AdminSiswaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ortu': {
      id: '/admin/ortu'
      path: '/ortu'
      fullPath: '/admin/ortu'
      preLoaderRoute: typeof AdminOrtuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kelas': {
      id: '/admin/kelas'
      path: '/kelas'
      fullPath: '/admin/kelas'
      preLoaderRoute: typeof AdminKelasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/guru': {
      id: '/admin/guru'
      path: '/guru'
      fullPath: '/admin/guru'
      preLoaderRoute: typeof AdminGuruRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminGuruRoute: typeof AdminGuruRoute
  AdminKelasRoute: typeof AdminKelasRoute
  AdminOrtuRoute: typeof AdminOrtuRoute
  AdminSiswaRoute: typeof AdminSiswaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminGuruRoute: AdminGuruRoute,
  AdminKelasRoute: AdminKelasRoute,
  AdminOrtuRoute: AdminOrtuRoute,
  AdminSiswaRoute: AdminSiswaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface GuruRouteRouteChildren {
  GuruCatatObservasiRoute: typeof GuruCatatObservasiRoute
  GuruObservasiMingguanRoute: typeof GuruObservasiMingguanRoute
  GuruRingkasanRoute: typeof GuruRingkasanRoute
  GuruIndexRoute: typeof GuruIndexRoute
}

const GuruRouteRouteChildren: GuruRouteRouteChildren = {
  GuruCatatObservasiRoute: GuruCatatObservasiRoute,
  GuruObservasiMingguanRoute: GuruObservasiMingguanRoute,
  GuruRingkasanRoute: GuruRingkasanRoute,
  GuruIndexRoute: GuruIndexRoute,
}

const GuruRouteRouteWithChildren = GuruRouteRoute._addFileChildren(
  GuruRouteRouteChildren,
)

interface OrtuRouteRouteChildren {
  OrtuIndexRoute: typeof OrtuIndexRoute
}

const OrtuRouteRouteChildren: OrtuRouteRouteChildren = {
  OrtuIndexRoute: OrtuIndexRoute,
}

const OrtuRouteRouteWithChildren = OrtuRouteRoute._addFileChildren(
  OrtuRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  GuruRouteRoute: GuruRouteRouteWithChildren,
  OrtuRouteRoute: OrtuRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
